language: node_js
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js:
        - 10
        - 12
      before_install:
      # Create a master branch for commitlint
      # https://github.com/conventional-changelog/commitlint/issues/6
      - git remote set-branches origin master && git fetch
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - rackup  # start a Web server
        - sleep 3 # give Web server some time to bind to sockets, etc
      dist: xenial
      services:
      - xvfb
      script: xvfb-run make test
      deploy:
        on:
          branch: master
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
